#!/bin/sh -e

# create the log directory if it doesn't exist
[ -d /var/log/gonano/openvpn ] || mkdir -p /var/log/gonano/openvpn

# tell svlogd to drop the stdout into our custom location
cd /var/log/gonano/openvpn
exec svlogd -v -ttt /var/log/gonano/openvpn
