#!/bin/sh -e

# export the path to be sure it's set properly
export PATH="/data/sbin:/data/bin:/opt/gonano/sbin:/opt/gonano/bin:/opt/local/sbin:/opt/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

# command to run openvpn
exec openvpn --config /data/etc/openvpn/openvpn.conf
