#!/usr/bin/env ruby

# hookit is installed as a bundled app, so we need bundler to load it for us
$:.unshift  '/opt/gonano/hookit/vendor/bundle'
require 'bundler/setup'

# load hookit/setup to bootstrap hookit and import the dsl
require 'hookit/setup'

require 'json'

keys = {}
keys["ca.crt"] = File.read("/data/var/db/openvpn/pki/ca.crt")
keys["client.key"] = File.read("/data/var/db/openvpn/pki/private/client1.key")
keys["client.crt"] = File.read("/data/var/db/openvpn/pki/issued/client1.crt")

puts keys.to_json
