#!/usr/bin/env ruby

# hookit is installed as a bundled app, so we need bundler to load it for us
$:.unshift  '/opt/gonano/hookit/vendor/bundle'
require 'bundler/setup'

# load hookit/setup to bootstrap hookit and import the dsl
require 'hookit/setup'

if File.exist?('/opt/gonano/etc/narc.conf')
  # create the runit definitions for narc
  directory '/etc/service/narc' do
    recursive true
  end

  directory '/etc/service/narc/log' do
    recursive true
  end

  hook_file '/etc/service/narc/log/run' do
    source 'runit/narc-log'
    mode 0755
  end

  hook_file '/etc/service/narc/run' do
    source 'runit/narc'
    mode 0755
  end

  service 'narc' do
    action :enable
  end
end

# create the runit definitions for openvpn
directory '/etc/service/openvpn' do
  recursive true
end

directory '/etc/service/openvpn/log' do
  recursive true
end

hook_file '/etc/service/openvpn/log/run' do
  source 'runit/openvpn-log'
  mode 0755
end

hook_file '/etc/service/openvpn/run' do
  source 'runit/openvpn'
  mode 0755
end

service 'openvpn' do
  action :enable
end
