#!/usr/bin/env ruby

# hookit is installed as a bundled app, so we need bundler to load it for us
$:.unshift  '/opt/gonano/hookit/vendor/bundle'
require 'bundler/setup'

# load hookit/setup to bootstrap hookit and import the dsl
require 'hookit/setup'

# Stop openvpn
service 'openvpn' do
  action :disable
  not_if { !Dir.exist?('/etc/service/openvpn') }
end

# Remove openvpn runit definition
directory '/etc/service/openvpn' do
  action :delete
  not_if { !Dir.exist?('/etc/service/openvpn') }
end

# Stop narc
service 'narc' do
  action :disable
  not_if { !Dir.exist?('/etc/service/narc') }
end

# Remove narc runit definition
directory '/etc/service/narc' do
  action :delete
  not_if { !Dir.exist?('/etc/service/narc') }
end
